export interface WorkersInterface{
    apellido?: string;
    nombre?: string;
    grado?: string;
    especialidad?: string;
    seccion?: string;
    codigo?: string;
    departamento?: string;
    municipio?: string;
    nacionalidad?: string;
    dia?: string;
    mes?: number;
    anio?: string;
    direccion?: string;    
    telefono ?: string;
    transporte ?: string;
    parvularia ?: string;
    primerCiclo ?: string;
    segundoCiclo ?: string;
    tercerCiclo ?: string;
    turno ?: string;
    hermano1 ?: string;
    gradoh1 ?: string;
    codh1 ?: string;
    hermano2 ?: string;
    gradoh2 ?: string;
    codh2 ?: string;
    religion?: string;
    alergia?: string;
    alergiRespuesta?: string;
    impedimento?: string;
    fiebre?: string;
    dolordeestomago?: string;
    dolordecabeza?: string;
    medicamentopermanente?: string;
    grupo?: string;
    conocimiento?: string;
    miembros?: string;

    papa?: string;
    papad?: string;
    papatel?: string;
    papacel?: string;
    papaprofesion?: string;
    papalugardt?: string;
    papateltrabajo?: string;
    papareligion?: string;
    papagrupo?: string;
    papaiglesia?: string;

    mama?: string;
    mamad?: string;
    mamatel?: string;
    mamacel?: string;
    mamaprofesion?: string;
    mamalugardt?: string;
    mamateltrabajo?: string;
    mamareligion?: string;
    mamagrupo?: string;
    mamaiglesia?: string;

    encargado?: string;
    parentesco?: string;
    encargadotel?: string;
    encargadocel?: string;
    encargadodirc?: string;
    encargadoprofesion?: string;
    encargadolugardt?: string;
    encargadoteltrabajo?: string;

    id?: string;
}